(function(){
const SEEN='scPopupSeenV16:',ADI='scAdRotationV16';
const val=(o,k)=>{for(const x of k)if(o&&o[x]!=null&&String(o[x]).trim())return String(o[x]).trim();return''},esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),img=o=>window.scRecordImage?window.scRecordImage(o):val(o,['Image URL','Image','Event Image','Ad Image','Photo URL','Photo']);
function stamp(o){const n=Date.parse(val(o,['Published At','Created At','Start Date','Event Date','Date','Timestamp']));return isNaN(n)?0:n}
function active(o){let x=val(o,['Start Date']);if(x){let d=new Date(x);if(!isNaN(d)){d.setHours(0,0,0,0);if(d>new Date())return false}}x=val(o,['End Date']);if(x){let d=new Date(x);if(!isNaN(d)){d.setHours(23,59,59,999);if(d<new Date())return false}}return true}
function good(o){return !!(o&&active(o)&&(val(o,['Notification Title','Event Title','Title','Ad Title','Full Name','Name'])||val(o,['Description','Details','Message','Content','Summary','Ad Description'])||img(o)))}
function key(o,t){return SEEN+t+':'+val(o,['ID','Id','id','Notification Title','Event Title','Title','Full Name','Name'])+':'+stamp(o)}
function dest(o,t){return val(o,['Related Page','Target URL','Related URL','More Info Link','Link URL','Link','URL','Registration Link'])||(t==='welcome'?'p/change-makers.html':t==='news'?'p/news.html':(t==='event'||t==='announcement')?'p/events.html':'p/notifications.html')}
function close(){document.getElementById('scV16Popup')?.remove()}
function show(o,t,auto){if(!good(o))return false;close();const hi=(localStorage.getItem('scLanguage')||'en')==='hi',title=(hi&&val(o,['Notification Title Hindi','Event Title Hindi','Title Hindi','Full Name Hindi']))||val(o,['Notification Title','Event Title','Title','Ad Title','Full Name','Name'])||(t==='welcome'?'Welcome to Change Makers':'Sursand Connect'),desc=(hi&&val(o,['Description Hindi']))||val(o,['Description','Details','Message','Content','Summary','Ad Description']),im=img(o),url=dest(o,t),sd=val(o,['Start Date','Event Date','Date']),ed=val(o,['End Date']),st=val(o,['Start Time','Event Time','Time']),et=val(o,['End Time']),meta=[];if(sd)meta.push('📅 <b>Start:</b> '+esc(sd)+(st?' • '+esc(st):''));if(ed)meta.push('🏁 <b>End:</b> '+esc(ed)+(et?' • '+esc(et):''));const w=document.createElement('div');w.id='scV16Popup';w.innerHTML='<div class="pc"><button class="x">×</button>'+(im?'<img class="pi" src="'+esc(im)+'" alt="">':'')+'<div class="pb">'+(t==='ad'?'<span class="tag">Advertisement</span>':'')+'<h2>'+esc(title)+'</h2>'+(meta.length?'<div class="pm">'+meta.join('<br>')+'</div>':'')+(desc?'<div class="pd">'+esc(desc).replace(/\n/g,'<br>')+'</div>':'')+(url?'<a class="pv" href="'+esc(url)+'">View Full Details</a>':'')+'</div></div>';document.body.appendChild(w);w.querySelector('.x').onclick=close;if(auto)setTimeout(close,6000);return true}
const css=document.createElement('style');css.textContent='#scV16Popup{position:fixed;inset:0;z-index:2200000;background:rgba(15,23,42,.6);display:flex;align-items:center;justify-content:center;padding:16px}.pc{width:min(92vw,520px);max-height:78vh;overflow:auto;background:#fff;border-radius:23px;box-shadow:0 28px 80px rgba(0,0,0,.34);position:relative}.x{position:absolute;right:9px;top:9px;z-index:3;width:34px;height:34px;border:0;border-radius:50%;background:rgba(15,23,42,.82);color:#fff;font-size:21px}.pi{width:100%;height:230px;object-fit:cover;display:block}.pb{padding:16px}.pb h2{font-size:19px;margin:3px 0 9px}.tag{display:inline-block;background:#fff0dd;color:#b45309;border-radius:999px;padding:5px 8px;font-size:8px;font-weight:900;margin-bottom:7px}.pm{padding:9px;background:#f8fafc;border-radius:11px;font-size:9px;line-height:1.6;margin-bottom:9px}.pd{font-size:10px;line-height:1.65;color:#475569}.pv{display:inline-flex;margin-top:12px;padding:10px 13px;border-radius:11px;background:#238b45;color:#fff;text-decoration:none;font-size:9px;font-weight:900}';document.head.appendChild(css);
function choose(d,allowAd){if(!d)return false;const a=[];(d.notifications||[]).forEach(o=>{if(!good(o))return;let welcome=/change maker welcome/i.test(val(o,['Category','Notification Type','Type']));a.push({o,t:welcome?'welcome':'notification',auto:welcome,z:stamp(o)})});(d.events||[]).forEach(o=>good(o)&&a.push({o,t:'event',auto:false,z:stamp(o)}));(d.announcements||[]).forEach(o=>good(o)&&a.push({o,t:'announcement',auto:false,z:stamp(o)}));(d.news||[]).forEach(o=>good(o)&&a.push({o,t:'news',auto:false,z:stamp(o)}));a.sort((x,y)=>y.z-x.z);const q=a.find(x=>!localStorage.getItem(key(x.o,x.t)));if(q){localStorage.setItem(key(q.o,q.t),String(Date.now()));return show(q.o,q.t,q.auto)}if(!allowAd)return false;const ads=(d.localAds||[]).filter(good);if(ads.length){const i=+(localStorage.getItem(ADI)||0);const ok=show(ads[i%ads.length],'ad',true);localStorage.setItem(ADI,String((i+1)%ads.length));return ok}return false}
async function run(){
 const cached=window.SCReadAllDataCache&&window.SCReadAllDataCache();
 if(cached&&choose(cached,false))return;
 try{const d=window.SCGetAllData?await window.SCGetAllData(true):null;if(d&&choose(d,false))return;if(d)choose(d,true);else if(cached)choose(cached,true)}
 catch(e){if(cached)choose(cached,true)}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run);else run();
})();